services:
  postgres-db:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: data_product
    ports:
      - "5433:5432"  # Map host's 5433 to container's 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laboratory_work_2
    depends_on:
      - postgres-db
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      - DB_HOST=postgres-db  # Matches the service name
      - DB_PORT=5432         # Internal PostgreSQL port
      - DB_NAME=data_product
      - DB_USER=postgres
      - DB_PASSWORD=admin1234
    restart: unless-stopped


volumes:
  postgres_data:
